name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt httpx pytest pytest-asyncio

      - name: Run tests
        run: python -m pytest tests/ -q

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t service-lens:latest .

      - name: Deploy container
        run: |
          docker stop service-lens 2>/dev/null || true
          docker rm service-lens 2>/dev/null || true
          docker run -d \
            --name service-lens \
            --restart unless-stopped \
            -p 8080:8080 \
            -v service-lens-data:/app/data \
            -v /var/run/docker.sock:/var/run/docker.sock:ro \
            -e UNRAID_HOST=${{ secrets.UNRAID_HOST }} \
            -e UNRAID_API_KEY=${{ secrets.UNRAID_API_KEY }} \
            -e UNRAID_VERIFY_SSL=false \
            service-lens:latest

      - name: Verify deployment
        run: |
          sleep 5
          curl -f http://localhost:8080/ || echo "Warning: health check failed"

      - name: Cleanup old images
        run: docker image prune -f --filter "dangling=true"
